#!/bin/sh

CMD_MYSQL="mysql -u${MYSQL_USER} -p${MYSQL_PASSWORD} ${MYSQL_DATABASE}"

#USERS
$CMD_MYSQL -e "create table ${MYSQL_USERS_TABLE} (
    ${MYSQL_USERS_TABLE_ID} int(16)  AUTO_INCREMENT,
    ${MYSQL_USERS_TABLE_NAME} varchar(32) NOT NULL,
    ${MYSQL_USERS_TABLE_TEXT} varchar(2048) NOT NULL,
    ${MYSQL_USERS_TABLE_DOSUBMIT} tinyint(1) NOT NULL DEFAULT 0,
    ${MYSQL_USERS_TABLE_CREATEDAT} DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ${MYSQL_USERS_TABLE_UPDATEDAT} DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (${MYSQL_USERS_TABLE_ID})
);"
#ROOMS
$CMD_MYSQL -e "create table ${MYSQL_ROOMS_TABLE} (
    ${MYSQL_ROOMS_TABLE_ID} int(16)  AUTO_INCREMENT,
    ${MYSQL_ROOMS_TABLE_NAME} varchar(32) NOT NULL,
    ${MYSQL_ROOMS_TABLE_DESCRIPTION} varchar(255) NOT NULL,
    ${MYSQL_ROOMS_TABLE_CREATEDAT} DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ${MYSQL_ROOMS_TABLE_UPDATEDAT} DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (${MYSQL_ROOMS_TABLE_ID})
);"
#ROOMUSER
$CMD_MYSQL -e "create table ${MYSQL_ROOMUSER_TABLE} (
    ${MYSQL_USERS_TABLE_ID} int(16) NOT NULL,
    ${MYSQL_ROOMS_TABLE_ID} int(16) NOT NULL,
    ${MYSQL_ROOMUSER_TABLE_CREATEDAT} DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ${MYSQL_ROOMUSER_TABLE_UPDATEDAT} DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (${MYSQL_USERS_TABLE_ID},${MYSQL_ROOMS_TABLE_ID})
);"